# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: apim-test

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  region: ${opt:region, 'West US 2'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  prefix: sprkt3
  resourceGroup: ${opt:rg}
  # type: premium
  # Azure subscription ID for deployment, allow for command line arg --subid to override
  subscriptionId: ${opt:subid}

  environment: # these will be created as application settings
    VARIABLE_FOO: 'foo'

  apim:
    sku:
      name: consumption
    apis:
      - name: salute-api
        subscriptionRequired: false # if true must provide an api key
        displayName: salute
        description: Salute sample app APIs
        protocols:
          - https
        path: salute
        authorization: none
    backends:
      - name: salute-backend
        url: api
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  # include:
  #   - include-me.js
  #   - include-me-dir/**
  exclude:
    # - exclude-me.js
    # - exclude-me-dir/**
    - local.settings.json
    - .vscode/**

functions:
  hello:
    handler: src/handlers/hello.sayHello
    # API Management configuration for `hello` handler
    apim:
      # The API to attach this operation
      api: salute-api
      # The Backend use for the operation
      backend: salute-backend
      operations:
        # GET operation for `sayHello` handler
        - method: get
          # URL path for accessing handler
          urlTemplate: hello
          # Display name inside Azure Portal
          displayName: Hello
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
          route: hello

  goodbye:
    handler: src/handlers/goodbye.sayGoodbye
     # API Management configuration for `hello` handler
    apim:
      # The API to attach this operation
      api: salute-api
      # The Backend use for the operation
      backend: salute-backend
      operations:
        # GET operation for `sayHello` handler
        - method: get
          # URL path for accessing handler
          urlTemplate: bye
          # Display name inside Azure Portal
          displayName: Goodbye
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
          route: bye
